### ISSUE TITLE
missing duration in summary.json

### ISSUE THREAD

**Issue by KaterinaUK** [wix-incubator/jest-allure2-reporter#26]
I wonder if you might be able to help me with this problem, I have my generated files, and looking at the allure-report/widgets/summary.json file, which contains:

`{"reportName":"Allure Report","testRuns":[],"statistic":{"failed":0,"broken":0,"skipped":0,"passed":6,"unknown":0,"total":6},"time":{"stop":1707496717173}}
`

Im trying to use this notifications plugin https://github.com/qa-guru/allure-notifications, which is expecting start, duration, minDuration, maxDuration, sumDuration:

`{
  "reportName" : "Allure Report",
  "testRuns" : [ ],
  "statistic" : {
    "failed" : 182,
    "broken" : 70,
    "skipped" : 118,
    "passed" : 439,
    "unknown" : 42,
    "total" : 851
  },
  "time" : {
    "start" : 1590795193703,
    "stop" : 1590932641296,
    "duration" : 11311,
    "minDuration" : 7901,
    "maxDuration" : 109870,
    "sumDuration" : 150125
  }
}`

might you know why these are missing on my summary.json file?

**Comment by KaterinaUK** [comment]
@noomorph 👋

**Comment by noomorph** [comment]
Hmm, this is interesting. I see "duration" in our reports. Can it be somehow related to the fact that you had configuration issues in #27  ?

**Comment by noomorph** [comment]
@KaterinaUK looks like this one may be relevant for you: https://github.com/qa-guru/allure-notifications/issues/183

**Comment by KaterinaUK** [comment]
> @KaterinaUK looks like this one may be relevant for you: [qa-guru/allure-notifications#183](https://github.com/qa-guru/allure-notifications/issues/183)

not quite the same issue, he had more of the duration attributes than I did.

my issue must have been due to missing:

"detox-allure2-adapter"
"jest-metadata"

and/or the testEnvironment

have it all setup as per the readme here https://github.com/wix-incubator/detox-allure2-adapter
