### ISSUE TITLE
testEnvironment: 'jest-allure2-reporter/environment-node'

### ISSUE THREAD

**Issue by KaterinaUK** [wix-incubator/jest-allure2-reporter#27]
the readme suggests setting the testEnvironment of the jest config jest.config.js to 

`testEnvironment: 'jest-allure2-reporter/environment-node'`

previously it was set as

`testEnvironment: 'detox/runners/jest/testEnvironment',`

When I change this I get errors when running detox tests:

` DetoxRuntimeError: Detox worker instance has not been installed in this context (DetoxSecondaryContext).`

I tried to lookup with jest docs what testEnvironment is for, but it is confusing, it seems any value but the one suggest in detox docs results in this error.

Can I enter multiple values for testEnvironment? if so how? what features of the allure report are missing without this? im wondering if it might be the root cause of my other issue: https://github.com/wix-incubator/jest-allure2-reporter/issues/26

**Comment by KaterinaUK** [comment]
@noomorph 👋

**Comment by noomorph** [comment]
As this is the vanilla Allure reporter for Jest, I will close this issue (it is out of the scope).

Please consult with [detox-allure2-adapter README](https://github.com/wix-incubator/detox-allure2-adapter).

If there are integration issues after executing the instructions in README, [please open an issue there](https://github.com/wix-incubator/detox-allure2-adapter/issues).

Thanks for trying out the integration! 👍

**Comment by KaterinaUK** [comment]
brilliant, that all works perfectly, hooked up with allure-notifications too

I think I was just reading the wrong readme :)
