### ISSUE TITLE
Message error is shown twice in the report if test uses an assertion that trows an error directly

### ISSUE THREAD

**Issue by patriciazumo** [wix-incubator/jest-allure2-reporter#44]
When my test fails because an error was thrown directly (e.g. using `throw new Error(reason)`), the error message in the report is displayed twice, as in this example
![duplicated_error_msg_example](https://github.com/wix-incubator/jest-allure2-reporter/assets/166608402/8dbf5a93-7399-49a9-a5b2-a0b796dc4a96)

In the console, this does not happen, the error is displayed only once.
Do you have an idea of what I can change in my setup so the error is not duplicated in the report?

I am using:
Detox: 20.19.5
detox-allure2-adapter: 1.0.0-alpha.11
jest-allure2-reporter: 2.0.0-beta.22

Your help is much appreciated. Thank you!

**Comment by noomorph** [comment]
Hm, can I see some more details about the error. I am confused by `Error:\nERROR\n`... why two times in different case? 🤔 

I assume you see that once? And when you click to expand error details, you see the duplication below, right?

**Comment by noomorph** [comment]
![image](https://github.com/user-attachments/assets/279fcf56-d70d-4cf2-af76-02594db1dfd2)

I tried to reproduce this issue but it seems that it is missing some important details... 🤔

**Comment by noomorph** [comment]
Sorry, I was wrong! There is some magic in putting `\nERROR` there in the message. I will take a look

**Comment by patriciazumo** [comment]
yeah, my error message starts with `\n` but it doesn't have to :) Thank you for checking this

**Comment by noomorph** [comment]
In any case, this is a nice catch. I will fix it soon.
