### ISSUE TITLE
Step is labeled as failed if it fails using a Jest expect extension but the test is labeled as passed

### ISSUE THREAD

**Issue by patriciazumo** [wix-incubator/jest-allure2-reporter#45]
I want to compare 2 values and fail the test with a custom message error if those values are different.
For that, I created an extension to the Jest expect that looks like this:

```
import { expect } from '@jest/globals'

expect.extend({
  toBeEqualWithCustomErrorMessage(expected: any, received: any, customErrorMessage: string) {
    const pass = received === expected
    const message = pass ? () => `\nPASSED:\nExpected: ${expected}\nActual: ${received}\n` : () => customErrorMessage

    return { pass, message }
  },
})

declare module 'expect' {
  interface Matchers<R> {
    toBeEqualWithCustomErrorMessage(expected: any, customErrorMessage: string): R
  }
}
```

Since I am using Detox Expect in my test steps, I created an auxiliar function that calls the one above:

```
export const isTheExpectedValue = (expected: string, actual: string, errorMessage: string): void => {
  expect(actual).toBeEqualWithCustomErrorMessage(expected, errorMessage)
}
```

And then, call this later function in the step, like this:
```
export const checkIsTheExpected = allure.createStep('Checking values', async (): Promise<void> => {
  isTheExpectedValue('banana', 'avocado', 'Banana is not avocado.')
})
```

The step is labeled as failed, as expected, and the custom error message is shown in the Allure report but the test is labeled as passed.
![jest_expect_extension_report](https://github.com/wix-incubator/jest-allure2-reporter/assets/166608402/0c43c997-2ebe-411c-af1f-9ed564a6bc17)

Do you know what I may be missing, so the test is labeled as failed too?

Thank you!

**Comment by noomorph** [comment]
I see. Let me check your example. I'll try to reproduce what you wrote.

**Comment by noomorph** [comment]
@patriciazumo , I managed to reproduce your issue. I think you forgot to use `await`.

You use async here:

export const checkIsTheExpected = allure.createStep('Checking values', **async (): Promise<void> => {**
  isTheExpectedValue('banana', 'avocado', 'Banana is not avocado.')
})

Which means, that your `checkIsTheExpected` is an async function:

![image](https://github.com/user-attachments/assets/fd371566-747c-447d-95fa-7fe543cf65bf)

If you are sure you have that `await` statement, feel free to reopen and please provide more details.

**Comment by patriciazumo** [comment]
copy+paste mistake of mine 🤦‍♀️ there's no reason for `checkIsTheExpected` to be an async function. I changed that and now the test is also labeled as failed, as you said. Thank you and I'm sorry to bother you with this!
